### ISSUE TITLE
Add ability to load and dump cloud product information

### ISSUE THREAD

**Issue by lpuskas** [banzaicloud/cloudinfo#134]
cached information can be easily exported and imported
This functionality allows a quicker recover and start (during development or production)

**Comment by sagikazarmark** [comment]
IMHO the data should not be treated as "cache". Cache would be a valid classification if upon a cache miss the data would be regenerated and returned to the consumer in the same request. As far as I can tell this is not the case.

The behavior of cloudinfo is more like an index in a search engine which contains information from several sources for faster searching/listing. Search engines usually version the data stored inside (per record). The difference here is versioning is not necessary on the record level, but on the whole index level. (Although I can imagine a record level versioning in a future implementation)

Especially since exporting/importing feature is requested, I would probably try to push the data storage model to this direction instead of keeping the current caching model. You could even try to use a real search engine for the job, but given the size of the dataset, that's probably not necessary.

**Comment by lpuskas** [comment]
We only use the "cache" (a library) here as a quick solution for (in-memory) storage. Historically it was thought as a temporary quick and dirty solution that later proved to be enough - however the storage -logic has been separated so that any other storage solution can be added. 

So you're right,  the data here doesn't have to be treated as a "real" cache, all the functionalities (import, export) this implementation supports can be migrated to some other backend solution...

**Comment by lpuskas** [comment]
fixed by #139
