### ISSUE TITLE
Azure pricing mismatch

### ISSUE THREAD

**Issue by Tzvetelin88** [banzaicloud/cloudinfo#294]
**Describe the bug**
For example: when checking: https://banzaicloud.com/cloudinfo/?provider=azure&service=compute&region=eastus2  I see price for Standard_A7  at  0.88000$, but looking at Azure calculator the price is 1.2$

**Steps to reproduce the issue:**
Please check https://azure.microsoft.com/en-gb/pricing/calculator/#virtual-machinesa3e7698f-9639-4ebe-88f7-bf34554196f1

**Expected behavior**
When filtering by "Cloud Services" and "Regions" at https://banzaicloud.com/ should return correct prices.
Filter is based only on a "Cloud Services" and "Regions", but pricing is changing when you have different "Operation system: Windows/Linux". Is it possible to filter with OS? 

Do you use Azure API: https://management.azure.com/subscriptions/{subscription-Id}/providers/Microsoft.Commerce/RateCard ?

**Screenshots**

**Additional context**
Very nice project! Good Work! Thanks for that

**Comment by lpuskas** [comment]
Hi Tzvetelin88,

We didn't emphasise it in the documentation, but cloudinfo scrapes the prices of compute resources without a paid OS/software because

1) it would add a complexity that we didn't want to cope with,
2) software offerings of different providers are not really comparable,
3) we didn't have a use case for using license sold by cloud providers.

The price of the resource that you asked for is the same (0.88000$) when asked from CloudInfo and in the calculator given that you choose Linux/CentOS as OS.

We will add a note about this to the documentation and the web UI, but if you could provide a pull request, that enables such functionality across all the supported providers, keeping it optional (i.e. can be disabled in config), we are glad to integrate it. Anyway if you decide to do this, please join our Community Slack, and talk about it

We use the RateCard API and other APIs like the Azure Compute API to process the price information and the details of the Azure offerings. CloudInfo combines the information retrieved through these APIs, and similar APIs of other providers.

Please let us know if you find any other issues with the service, thanks

**Comment by Tzvetelin88** [comment]
Which is the best way to contact you, as I have some questions? I'm working for a company which is golden partner of Microsoft. I raise them a support case for Azure API Prices and which is the best way to retrieve resource prices. RateCard is very old API version and it's saying in Preview.

**Comment by sagikazarmark** [comment]
@Tzvetelin88 you can contact us directly on Slack:  https://slack.banzaicloud.io/
